language: node_js
node_js: stable

cache:
  directories:
    - node_modules
before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_d5da0d5a1b17_key -iv $encrypted_d5da0d5a1b17_iv -in .travis/secrets.tar.enc -out ~/.ssh/secrets.tar -d
  - tar xvf ~/.ssh/secrets.tar
  # Set the permission of the key
  - chmod 600 ~/.ssh/*
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/coding
  - ssh-add ~/.ssh/githubhexoblog
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name "ganli"
  - git config --global user.email gl09025@gmail.com
  # Install Hexo
  - npm install hexo@beta -g
  # Clone the repository
  - git clone https://github.com/gl09025/hexo-blog.git .deploy

script:
  - hexo generate
  - hexo deploy
  # - cd public
  # - git init
  # - git remote add origin https://$coding_name:$coding_password@git.coding.net/gl09025/hexoblog.git
  # - git add .
  # - git commit -m "update hexoblog in coding"
  # - git push -f origin master
branches:
  only:
    - blog-resource
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify